import { z } from 'zod';
import { containsUnsafeText } from '../dictionary/validation.js';
import { ALLOWED_PARTICIPANT_KEYS } from '../auth/allowed-participants.js';

// --- Client-submitted transcript (PUT .../discussion/transcript) ---

export const TRANSCRIPT_SEGMENT_TEXT_MAX_LENGTH = 1000;
export const TRANSCRIPT_MAX_SEGMENTS = 300;
export const TRANSCRIPT_TOTAL_TEXT_MAX_LENGTH = 50_000;
const SEGMENT_ID_MAX_LENGTH = 100;

const URL_PATTERN = /(?:https?:\/\/|www\.)/i;
const HTML_TAG_PATTERN = /<\/?[A-Za-z!][^>]*>/;

/** Rejects control characters, HTML tags, and raw URLs — never trust client-supplied transcript text. */
const transcriptSegmentTextSchema = z
  .string()
  .trim()
  .min(1, 'segment text must not be blank')
  .max(
    TRANSCRIPT_SEGMENT_TEXT_MAX_LENGTH,
    `segment text must be at most ${TRANSCRIPT_SEGMENT_TEXT_MAX_LENGTH} characters`,
  )
  .refine((value) => !containsUnsafeText(value), 'segment text contains unsafe characters')
  .refine((value) => !HTML_TAG_PATTERN.test(value), 'segment text must not contain HTML tags')
  .refine((value) => !URL_PATTERN.test(value), 'segment text must not contain a raw URL');

const speakerKeySchema = z.union([z.enum(ALLOWED_PARTICIPANT_KEYS), z.null()]);

export const transcriptSegmentSchema = z
  .object({
    id: z.string().trim().min(1).max(SEGMENT_ID_MAX_LENGTH),
    startMs: z.number().int().nonnegative(),
    endMs: z.number().int().nonnegative(),
    text: transcriptSegmentTextSchema,
    speakerKey: speakerKeySchema,
  })
  .strict()
  .refine((segment) => segment.endMs > segment.startMs, {
    message: 'endMs must be greater than startMs',
    path: ['endMs'],
  });

export const putTranscriptRequestSchema = z
  .object({
    topicIndex: z.number().int().min(0).max(2),
    segments: z.array(transcriptSegmentSchema).min(1).max(TRANSCRIPT_MAX_SEGMENTS),
  })
  .strict()
  .refine(
    (body) =>
      body.segments.reduce((sum, segment) => sum + segment.text.length, 0) <=
      TRANSCRIPT_TOTAL_TEXT_MAX_LENGTH,
    {
      message: `total transcript text must be at most ${TRANSCRIPT_TOTAL_TEXT_MAX_LENGTH} characters`,
      path: ['segments'],
    },
  );

export type PutTranscriptRequest = z.infer<typeof putTranscriptRequestSchema>;

// --- Schema Mindlogic's structured feedback output is validated against ---

const SUMMARY_MAX_LENGTH = 800;
const COMMENT_MAX_LENGTH = 400;
const QUESTION_MAX_LENGTH = 300;
const DISPLAY_NAME_MAX_LENGTH = 80;
const STRENGTH_MAX_LENGTH = 200;
const IMPROVEMENT_FIELD_MAX_LENGTH = 300;
const EXPRESSION_MAX_LENGTH = 150;
const TIP_MAX_LENGTH = 200;
const MAX_STRENGTHS = 6;
const MAX_IMPROVEMENTS = 6;
const MAX_EXPRESSIONS = 6;
const MAX_TIPS = 5;

/** Free text generated by the model — content-safety-checked the same way as ai-lookup.ts's safeShortText. */
function safeText(max: number, label: string) {
  return z
    .string()
    .transform((value) => value.normalize('NFKC').trim())
    .pipe(
      z
        .string()
        .min(1, `${label} must not be blank`)
        .max(max, `${label} must be at most ${max} characters`)
        .refine((value) => !containsUnsafeText(value), `${label} contains unsafe characters`)
        .refine((value) => !HTML_TAG_PATTERN.test(value), `${label} must not contain HTML tags`),
    );
}

const improvementSchema = z
  .object({
    original: safeText(IMPROVEMENT_FIELD_MAX_LENGTH, 'improvements[].original'),
    suggested: safeText(IMPROVEMENT_FIELD_MAX_LENGTH, 'improvements[].suggested'),
    explanation: safeText(IMPROVEMENT_FIELD_MAX_LENGTH, 'improvements[].explanation'),
  })
  .strict();

const participantFeedbackSchema = z
  .object({
    participantKey: z.enum(ALLOWED_PARTICIPANT_KEYS),
    displayName: safeText(DISPLAY_NAME_MAX_LENGTH, 'participants[].displayName'),
    strengths: z.array(safeText(STRENGTH_MAX_LENGTH, 'strengths[]')).max(MAX_STRENGTHS),
    improvements: z.array(improvementSchema).max(MAX_IMPROVEMENTS),
    usefulExpressions: z
      .array(safeText(EXPRESSION_MAX_LENGTH, 'usefulExpressions[]'))
      .max(MAX_EXPRESSIONS),
    // Always overwritten server-side after validation (see
    // generate-feedback.ts) — never trust the model's own figure. Optional
    // here purely so the pre-overwrite parse doesn't reject a response
    // that already omits it.
    speakingShare: z.number().min(0).max(100).optional(),
  })
  .strict();

/**
 * Re-validated with Zod after parsing the model's JSON, independent of
 * the response_format JSON Schema sent in the request (see prompt.ts) —
 * mirrors reflections/schema.ts's reflectionComparisonSchema philosophy.
 * Additional guards beyond this structural check (participantKey set
 * matches the transcript's actual speakers, `improvements[].original` is
 * a real substring of that participant's transcript text) live in
 * generate-feedback.ts, since they need the transcript itself.
 */
export const discussionFeedbackResultSchema = z
  .object({
    overallSummary: safeText(SUMMARY_MAX_LENGTH, 'overallSummary'),
    topicCoverage: z
      .object({
        score: z.number().int().min(1).max(5),
        comment: safeText(COMMENT_MAX_LENGTH, 'topicCoverage.comment'),
      })
      .strict(),
    participants: z.tuple([participantFeedbackSchema, participantFeedbackSchema]),
    sharedDiscussionTips: z.array(safeText(TIP_MAX_LENGTH, 'sharedDiscussionTips[]')).max(MAX_TIPS),
    nextQuestion: safeText(QUESTION_MAX_LENGTH, 'nextQuestion'),
  })
  .strict();

export type DiscussionFeedbackAiResult = z.infer<typeof discussionFeedbackResultSchema>;
